### PR TITLE
Update AbstractDescriptor.php

### PR DESCRIPTION
**Pull request by lizjulien**
Fix for $object->getViolations(), must get an object to call ->filter()

### CODE REVIEW

**Comment by lyrixx** [comment]
Good catch, thanks @lizjulien.

**Comment by stof** [comment]
it which case could it be something else ?

**Comment by lizjulien** [comment]
@stof Maybe no violations ?

**Comment by stof** [comment]
Well, if the API returns a collection object, it should return an empty collection, but still return a collection

**Comment by lyrixx** [comment]
I guess it's because of the (de)serializer

**Comment by stof** [comment]
than I suggest fixing the deserializer instead

**Comment by lyrixx** [comment]
@stof I agree with you. But unfortunately I have no time for that :/

**Pull request merged**
